services:
  database:
    image: mongo
    restart: unless-stopped
    networks:
      - navtrack
    environment:
      MONGO_INITDB_ROOT_USERNAME: navtrack
      MONGO_INITDB_ROOT_PASSWORD: navtrack
    volumes:
      - navtrack:/data/db
    ports:
      - 27017:27017

volumes:
  navtrack:

networks:
  navtrack:
