name: Publish Docker Images

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  publish:
    if: github.repository == 'navtrack/navtrack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: |
          ./build-docker-images.sh
      - name: Docker push
        run: |
          docker tag navtrack/api ghcr.io/navtrack/navtrack/api
          docker tag navtrack/web ghcr.io/navtrack/navtrack/web
          docker tag navtrack/listener ghcr.io/navtrack/navtrack/listener
          docker push ghcr.io/navtrack/navtrack/api
          docker push ghcr.io/navtrack/navtrack/web
          docker push ghcr.io/navtrack/navtrack/listener
